- name: Install dependencies
  apt:
    pkg:
    - git 
    - curl 
    - autoconf 
    - bison 
    - build-essential
    - libssl-dev 
    - libyaml-dev 
    - libreadline6-dev 
    - zlib1g-dev
    - libncurses5-dev 
    - libffi-dev 
    - libgdbm6 
    - libgdbm-dev 
    - libdb-dev
  become: true

- name: Clone rbenv repo
  ansible.builtin.git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ ansible_user }}/.rbenv"

- name: Set rbenv config
  shell:
    cmd: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> {{ ansible_user }}/.bashrc | echo 'eval "$(rbenv init -)"' >> {{ ansible_user }}/.bashrc

- name: Source .bashrc
  shell:
    cmd: "source {{ ansible_user }}/.bashrc"