- name: Rbenv | Install dependencies
  apt:
    pkg:
    - git 
    - curl 
    - autoconf 
    - bison 
    - build-essential
    - libssl-dev 
    - libyaml-dev 
    - libreadline6-dev 
    - zlib1g-dev
    - libncurses5-dev 
    - libffi-dev 
    - libgdbm6 
    - libgdbm-dev 
    - libdb-dev
  become: true

- name: Rbenv | Clone rbenv repo
  ansible.builtin.git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "/home/{{ ansible_user }}/.rbenv"

- name: Rbenv | Set rbenv config
  shell:
    cmd: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/{{ ansible_user }}/.bashrc | echo 'eval "$(rbenv init -)"' >> /home/{{ ansible_user }}/.bashrc

- name: Rbenv | Source .bashrc
  shell:
    cmd: "source /home/{{ ansible_user }}/.bashrc"