- name: Sidekiq | Create sidekiq.service file
  ansible.builtin.file:
    path: "/etc/systemd/system/sidekiq.service"
    state: touch
  become: true

- name: Sidekiq | Set sidekiq config
  template:
    src: templates/sidekiq.j2
    dest: "/etc/systemd/system/sidekiq.service" 
  become: true
